import type { AchievementDef } from './achievement.types.js';
import { ACHIEVEMENT_CELEBRATE_DIALOG } from './achievement.types.js';

/** Static defaults synced into MongoDB on server start. */
export const ACHIEVEMENT_CATALOG_VERSION = 6;

/** Keys removed from the active catalog (kept in DB as hidden). */
export const RETIRED_ACHIEVEMENT_KEYS = [
  'profile-location',
  'profile-cv',
  'profile-education',
  'profile-work',
] as const;

export const ACHIEVEMENT_CATALOG: readonly AchievementDef[] = [
  {
    id: 'respect-given-1',
    slug: 'everyone-gets-one',
    title: 'Everyone gets an upvote!',
    description: 'Give your first Respect on a post.',
    category: 'engagement',
    module: 'engagement',
    points: 5,
    metric: 'respect.given.total',
    target: 1,
    celebrateAs: ACHIEVEMENT_CELEBRATE_DIALOG,
    sortOrder: 1,
  },
  {
    id: 'respect-given-3',
    slug: 'daily-syntax-readit',
    title: 'Daily Syntax Readit!',
    description: 'Give Respect on 3 posts.',
    category: 'engagement',
    module: 'engagement',
    points: 10,
    metric: 'respect.given.total',
    target: 3,
    celebrateAs: ACHIEVEMENT_CELEBRATE_DIALOG,
    sortOrder: 2,
  },
  {
    id: 'read-brief-4',
    slug: 'daily-syntax-reader',
    title: 'Daily Syntax Reader',
    description: 'Read 4 post briefings.',
    category: 'reading',
    module: 'reading',
    points: 15,
    metric: 'read.brief.total',
    target: 4,
    celebrateAs: ACHIEVEMENT_CELEBRATE_DIALOG,
    sortOrder: 3,
  },
  {
    id: 'posts-1',
    slug: 'daily-syntax-author',
    title: 'Daily Syntax Author',
    description: 'Publish your first blog post.',
    category: 'meta',
    module: 'blog',
    points: 15,
    metric: 'posts.authored.count',
    target: 1,
    celebrateAs: ACHIEVEMENT_CELEBRATE_DIALOG,
    sortOrder: 4,
  },
  {
    id: 'profile-avatar',
    slug: 'profile-picture',
    title: 'Profile Picture',
    description: 'Upload a profile picture.',
    category: 'profile',
    module: 'profile',
    points: 10,
    metric: 'profile.has_avatar',
    target: 1,
    celebrateAs: ACHIEVEMENT_CELEBRATE_DIALOG,
    sortOrder: 5,
  },
  {
    id: 'profile-cover',
    slug: 'background-banner',
    title: 'Background Banner',
    description: 'Upload a cover / background image on your profile.',
    category: 'profile',
    module: 'profile',
    points: 10,
    metric: 'profile.has_cover',
    target: 1,
    celebrateAs: ACHIEVEMENT_CELEBRATE_DIALOG,
    sortOrder: 6,
  },
  {
    id: 'profile-bio',
    slug: 'bio-complete',
    title: 'Bio Complete',
    description: 'Write a bio on your profile.',
    category: 'profile',
    module: 'profile',
    points: 10,
    metric: 'profile.has_bio',
    target: 1,
    celebrateAs: ACHIEVEMENT_CELEBRATE_DIALOG,
    sortOrder: 7,
  },
  {
    id: 'profile-github',
    slug: 'github-connected',
    title: 'GitHub Connected',
    description: 'Link your GitHub profile or repository.',
    category: 'profile',
    module: 'profile',
    points: 10,
    metric: 'profile.has_github',
    target: 1,
    celebrateAs: ACHIEVEMENT_CELEBRATE_DIALOG,
    sortOrder: 8,
  },
  {
    id: 'stack-1',
    slug: 'stack-and-tools',
    title: 'Stack & Tools',
    description: 'Add your first skill to Stack & Tools.',
    category: 'profile',
    module: 'profile',
    points: 10,
    metric: 'stack.tools.count',
    target: 1,
    celebrateAs: ACHIEVEMENT_CELEBRATE_DIALOG,
    sortOrder: 10,
  },
  {
    id: 'profile-setup-1',
    slug: 'my-setup',
    title: 'My Setup',
    description: 'Add your first item to My Setup.',
    category: 'profile',
    module: 'profile',
    points: 10,
    metric: 'profile.setup.count',
    target: 1,
    celebrateAs: ACHIEVEMENT_CELEBRATE_DIALOG,
    sortOrder: 11,
  },
  {
    id: 'follow-authors-3',
    slug: 'follow-three-authors',
    title: 'Follow 3 Authors',
    description: 'Follow 3 writers on Syntax Stories.',
    category: 'social',
    module: 'social',
    points: 15,
    metric: 'social.following.count',
    target: 3,
    celebrateAs: ACHIEVEMENT_CELEBRATE_DIALOG,
    sortOrder: 12,
  },
  {
    id: 'follow-categories-3',
    slug: 'follow-three-categories',
    title: 'Follow 3 Categories',
    description: 'Follow 3 blog categories you care about.',
    category: 'social',
    module: 'blog',
    points: 15,
    metric: 'blog.categories.followed.count',
    target: 3,
    celebrateAs: ACHIEVEMENT_CELEBRATE_DIALOG,
    sortOrder: 13,
  },
  {
    id: 'squad-join-1',
    slug: 'squad-up',
    title: 'Squad Up',
    description: 'Join your first squad.',
    category: 'social',
    module: 'social',
    points: 15,
    metric: 'squads.joined.count',
    target: 1,
    celebrateAs: ACHIEVEMENT_CELEBRATE_DIALOG,
    sortOrder: 14,
  },
  {
    id: 'feedback-1',
    slug: 'first-feedback',
    title: 'First Feedback',
    description: 'Submit your first feedback to Syntax Stories.',
    category: 'meta',
    module: 'meta',
    points: 10,
    metric: 'feedback.submitted.count',
    target: 1,
    celebrateAs: ACHIEVEMENT_CELEBRATE_DIALOG,
    sortOrder: 15,
  },
  {
    id: 'invite-1',
    slug: 'invite-one-friend',
    title: 'Invite One Friend',
    description: 'A friend joined Syntax Stories using your invite.',
    category: 'social',
    module: 'social',
    points: 25,
    metric: 'referral.converted.total',
    target: 1,
    celebrateAs: ACHIEVEMENT_CELEBRATE_DIALOG,
    sortOrder: 16,
  },
  {
    id: 'invite-5',
    slug: 'invite-five-friends',
    title: 'Invite Five Friends',
    description: 'Five friends joined through your referral link.',
    category: 'social',
    module: 'social',
    points: 75,
    metric: 'referral.converted.total',
    target: 5,
    celebrateAs: ACHIEVEMENT_CELEBRATE_DIALOG,
    sortOrder: 17,
  },
  {
    id: 'invite-10',
    slug: 'invite-ten-friends',
    title: 'Community Builder',
    description: 'Ten friends joined through your invites.',
    category: 'social',
    module: 'social',
    points: 150,
    metric: 'referral.converted.total',
    target: 10,
    celebrateAs: ACHIEVEMENT_CELEBRATE_DIALOG,
    sortOrder: 18,
  },
] as const;

export const ACHIEVEMENT_TOTAL = ACHIEVEMENT_CATALOG.length;

export const ACHIEVEMENT_BY_ID = new Map(ACHIEVEMENT_CATALOG.map((a) => [a.id, a]));
