import {
  BLOG_THUMB_MAX_BYTES,
  IMAGE_UPLOAD_MAX_BYTES,
  PROFILE_RASTER_IMAGE_MAX_BYTES,
} from "@syntax-stories/shared";

export const PROFILE_RASTER_IMAGE_MAX_MB =
  PROFILE_RASTER_IMAGE_MAX_BYTES / (1024 * 1024);
export const BLOG_INLINE_IMAGE_MAX_MB =
  IMAGE_UPLOAD_MAX_BYTES.media / (1024 * 1024);
export const BLOG_THUMB_MAX_MB = BLOG_THUMB_MAX_BYTES / (1024 * 1024);

export {
  IMAGE_UPLOAD_MAX_BYTES,
  PROFILE_RASTER_IMAGE_MAX_BYTES,
  BLOG_THUMB_MAX_BYTES,
  SQUAD_LOGO_MAX_BYTES,
  SQUAD_BANNER_MAX_BYTES,
} from "@syntax-stories/shared";
