import { apiClient } from './client';

function getAuthBase(): string {
  const base = typeof window !== 'undefined'
    ? (process.env.NEXT_PUBLIC_API_BASE_URL ?? '')
    : (process.env.NEXT_PUBLIC_API_BASE_URL ?? '');
  return base ? `${base.replace(/\/$/, '')}/auth` : '/auth';
}

const AUTH_FETCH_TIMEOUT_MS = 28000; // 28s – avoid infinite "Sending..." when backend is cold or slow

export class AuthError extends Error {
  constructor(message: string, public status?: number) {
    super(message);
    this.name = 'AuthError';
  }
}

/** Called on 401 to try refresh; returns new access token or null. Set by store so any auth request can retry once. */
let authRetryHandler: (() => Promise<string | null>) | null = null;

export function setAuthRetryHandler(handler: (() => Promise<string | null>) | null) {
  authRetryHandler = handler;
}

async function authFetch<T>(path: string, options?: RequestInit & { token?: string }, isRetry = false): Promise<T> {
  const url = path.startsWith('http')
    ? path
    : typeof window !== 'undefined'
      ? `${window.location.origin}${path}`
      : `${process.env.NEXT_PUBLIC_API_BASE_URL ?? ''}${path}`;
  const token = options?.token;
  const { token: _, ...restOptions } = options ?? {};
  const headers: HeadersInit = {
    'Content-Type': 'application/json',
    ...restOptions?.headers,
  };
  if (token) (headers as Record<string, string>)['Authorization'] = `Bearer ${token}`;

  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), AUTH_FETCH_TIMEOUT_MS);
  let res: Response;
  try {
    res = await fetch(url, { ...restOptions, headers, signal: controller.signal });
  } catch (err) {
    clearTimeout(timeoutId);
    if (err instanceof Error && err.name === 'AbortError') {
      throw new Error('Request timed out. If the server is waking up, try again in a moment.');
    }
    throw err;
  }
  clearTimeout(timeoutId);
  const text = await res.text().catch(() => '');

  if (!res.ok) {
    if (res.status === 401 && token && !isRetry && authRetryHandler) {
      const newToken = await authRetryHandler();
      if (newToken) return authFetch<T>(path, { ...restOptions, token: newToken }, true);
    }
    try {
      const data = text ? (JSON.parse(text) as { message?: string; error?: Array<{ message?: string }> }) : null;
      const detail = data?.error?.[0]?.message;
      const msg = detail || data?.message || res.statusText || 'Request failed';
      throw new AuthError(msg, res.status);
    } catch (e) {
      if (e instanceof AuthError) throw e;
      if (e instanceof SyntaxError) throw new AuthError(text || res.statusText || 'Request failed', res.status);
      if (e instanceof Error) throw new AuthError(e.message, res.status);
      throw new AuthError(text || res.statusText || 'Request failed', res.status);
    }
  }

  if (!text) return {} as T;
  return JSON.parse(text) as T;
}

export interface SendOtpPayload {
  email: string;
}

export interface SignUpEmailPayload {
  fullName: string;
  email: string;
}

export interface VerifyOtpPayload {
  email: string;
  code: string;
}

export interface WorkExperience {
  /** Auto-generated by backend when work experience is added (WORK_ID display). */
  workId?: string;
  jobTitle?: string;
  employmentType?: string;
  company?: string;
  companyDomain?: string;
  currentPosition?: boolean;
  startDate?: string;
  endDate?: string;
  location?: string;
  locationType?: string;
  description?: string;
  skills?: string[];
  /** @deprecated use media */
  mediaUrls?: string[];
  /** Media items: links or uploaded images (url, title, altText) */
  media?: { url: string; title?: string; altText?: string }[];
  /** @deprecated use jobTitle */
  role?: string;
}
export interface EducationItem {
  /** Auto-generated by backend when education entry is added (EDU_ID display). */
  eduId?: string;
  school?: string;
  schoolDomain?: string;
  degree?: string;
  fieldOfStudy?: string;
  field?: string;
  currentEducation?: boolean;
  startDate?: string;
  endDate?: string;
  startYear?: number;
  endYear?: number;
  grade?: string;
  description?: string;
  activity?: string;
  /** Ref code like "2024_EDU_DOC", based on last update year. */
  refCode?: string;
}
export interface CertificationItem {
  /** Auto-generated by backend when certification is added (CERT_ID display). */
  certId?: string;
  name?: string;
  issuingOrganization?: string;
  currentlyValid?: boolean;
  issueDate?: string;
  expirationDate?: string;
  /** Auto-generated validation type, e.g. "A-24". */
  certValType?: string;
  credentialId?: string;
  credentialUrl?: string;
  description?: string;
  skills?: string[];
  media?: { url: string; title?: string; altText?: string }[];
}
export interface ProjectItem {
  type?: 'project' | 'publication';
  source?: 'github';
  repoFullName?: string;
  repoId?: number;
  title?: string;
  publisher?: string;
  ongoing?: boolean;
  publicationDate?: string;
  endDate?: string;
  publicationUrl?: string;
  description?: string;
  media?: { url: string; title?: string; altText?: string }[];
  /** Last updated year log from backend, e.g. "2025_prd_log". */
  prjLog?: string;
  /** @deprecated use title */
  name?: string;
  /** @deprecated use publicationUrl */
  url?: string;
}
export interface OpenSourceContribution {
  title?: string;
  repository?: string;
  repositoryUrl?: string;
  active?: boolean;
  activeFrom?: string;
  endDate?: string;
  description?: string;
  /** @deprecated use repository */
  repo?: string;
  /** @deprecated use repositoryUrl */
  url?: string;
}

export interface SetupItem {
  label: string;
  imageUrl: string;
  productUrl?: string;
}

export interface AuthUser {
  id: string;
  _id?: string;
  fullName?: string;
  username?: string;
  email: string;
  name?: string;
  profileImg?: string;
  image?: string;
  coverBanner?: string;
  bio?: string;
  job?: string;
  portfolioUrl?: string;
  linkedin?: string;
  instagram?: string;
  github?: string;
  youtube?: string;
  stackAndTools?: string[];
  workExperiences?: WorkExperience[];
  education?: EducationItem[];
  certifications?: CertificationItem[];
  projects?: ProjectItem[];
  openSourceContributions?: OpenSourceContribution[];
  mySetup?: SetupItem[];
  isGoogleAccount?: boolean;
  isGitAccount?: boolean;
  isFacebookAccount?: boolean;
    isXAccount?: boolean;
  isAppleAccount?: boolean;
  createdAt?: string;
}

export interface AccountResponse {
  user: {
    _id: string;
    fullName: string;
    username: string;
    email: string;
    profileImg?: string;
    coverBanner?: string;
    bio?: string;
    job?: string;
    portfolioUrl?: string;
    linkedin?: string;
    instagram?: string;
    github?: string;
    youtube?: string;
    stackAndTools?: string[];
    workExperiences?: WorkExperience[];
    education?: EducationItem[];
    certifications?: CertificationItem[];
    projects?: ProjectItem[];
    openSourceContributions?: OpenSourceContribution[];
    mySetup?: SetupItem[];
    isGoogleAccount?: boolean;
    isGitAccount?: boolean;
    isFacebookAccount?: boolean;
    isXAccount?: boolean;
    isAppleAccount?: boolean;
    twoFactorEnabled?: boolean;
    createdAt?: string;
  };
  message?: string;
}

export type UpdateProfilePayload = Partial<{
  fullName: string;
  username: string;
  bio: string;
  profileImg: string;
  coverBanner: string;
  job: string;
  portfolioUrl: string;
  linkedin: string;
  instagram: string;
  github: string;
  youtube: string;
  stackAndTools: string[];
  workExperiences: WorkExperience[];
  education: EducationItem[];
  certifications: CertificationItem[];
  projects: ProjectItem[];
  openSourceContributions: OpenSourceContribution[];
  mySetup: SetupItem[];
}>;

export interface VerifyOtpResponse {
  message: string;
  success: boolean;
  accessToken?: string;
  refreshToken?: string;
  expiresIn?: string;
  twoFactorRequired?: boolean;
  challengeToken?: string;
  isNewUser?: boolean;
  user: {
    _id: string;
    fullName: string;
    username: string;
    email: string;
    profileImg?: string;
  };
}

export interface VerifyTwoFactorLoginResponse {
  success: boolean;
  message: string;
  accessToken: string;
  refreshToken?: string;
  expiresIn?: string;
  user: {
    _id: string;
    fullName: string;
    username: string;
    email: string;
    profileImg?: string;
  };
}

export const authApi = {
  sendOtp: (data: SendOtpPayload) =>
    authFetch<{ message: string; success: boolean }>(`${getAuthBase()}/send-otp`, {
      method: 'POST',
      body: JSON.stringify(data),
    }),

  signupEmail: (data: SignUpEmailPayload) =>
    authFetch<{ message: string; success: boolean }>(`${getAuthBase()}/signup-email`, {
      method: 'POST',
      body: JSON.stringify(data),
    }),

  verifyOtp: (data: VerifyOtpPayload) =>
    authFetch<VerifyOtpResponse>(`${getAuthBase()}/verify-otp`, {
      method: 'POST',
      body: JSON.stringify(data),
    }),

  verifyTwoFactorLogin: (data: { challengeToken: string; token: string }) =>
    authFetch<VerifyTwoFactorLoginResponse>(`${getAuthBase()}/2fa/verify-login`, {
      method: 'POST',
      body: JSON.stringify(data),
    }),

  logout: (accessToken: string) =>
    authFetch<{ message: string; success: boolean }>(`${getAuthBase()}/logout`, {
      method: 'POST',
      token: accessToken,
    }),

  /** Revoke session by refresh token (no JWT). Call when clearing state after token expiry. */
  revokeSession: (refreshToken: string) =>
    authFetch<{ success: boolean; message?: string }>(`${getAuthBase()}/revoke-session`, {
      method: 'POST',
      body: JSON.stringify({ refreshToken }),
    }),

  refresh: (refreshToken: string) =>
    authFetch<{ success: boolean; accessToken: string; expiresIn?: string }>(`${getAuthBase()}/refresh`, {
      method: 'POST',
      body: JSON.stringify({ refreshToken }),
    }),

  getAccount: (accessToken: string) =>
    authFetch<AccountResponse>(`${getAuthBase()}/me`, {
      method: 'GET',
      token: accessToken,
    }),

  updateProfile: (accessToken: string, data: UpdateProfilePayload) =>
    authFetch<{ success: boolean; user: AccountResponse['user'] }>(`${getAuthBase()}/profile`, {
      method: 'PATCH',
      token: accessToken,
      body: JSON.stringify(data),
    }),

  disconnectProvider: (accessToken: string, provider: string) =>
    authFetch<{ success: boolean; message?: string }>(`${getAuthBase()}/disconnect/${provider}`, {
      method: 'POST',
      token: accessToken,
    }),

  /** Get redirect URL to link an OAuth provider to the current account. Call then set window.location = redirectUrl. */
  getLinkRedirectUrl: (accessToken: string, provider: 'google' | 'github' | 'facebook' | 'x') =>
    authFetch<{ success: boolean; redirectUrl?: string; message?: string }>(`${getAuthBase()}/link-request`, {
      method: 'POST',
      token: accessToken,
      body: JSON.stringify({ provider }),
    }),

  initEmailChange: (accessToken: string, newEmail: string) =>
    authFetch<{ success: boolean; message?: string }>(`${getAuthBase()}/email-change/init`, {
      method: 'POST',
      token: accessToken,
      body: JSON.stringify({ newEmail }),
    }),

  verifyEmailChange: (accessToken: string, currentCode: string, newCode: string) =>
    authFetch<{ success: boolean; message?: string }>(`${getAuthBase()}/email-change/verify`, {
      method: 'POST',
      token: accessToken,
      body: JSON.stringify({ currentCode, newCode }),
    }),

  cancelEmailChange: (accessToken: string) =>
    authFetch<{ success: boolean; message?: string }>(`${getAuthBase()}/email-change/cancel`, {
      method: 'POST',
      token: accessToken,
    }),
};

export function normalizeUser(backendUser: AccountResponse['user']): AuthUser {
  return {
    id: backendUser._id,
    _id: backendUser._id,
    email: backendUser.email,
    name: backendUser.fullName ?? backendUser.username ?? backendUser.email,
    fullName: backendUser.fullName,
    username: backendUser.username,
    profileImg: backendUser.profileImg,
    image: backendUser.profileImg,
    coverBanner: backendUser.coverBanner,
    bio: backendUser.bio,
    job: backendUser.job,
    portfolioUrl: backendUser.portfolioUrl,
    linkedin: backendUser.linkedin,
    instagram: backendUser.instagram,
    github: backendUser.github,
    youtube: backendUser.youtube,
    stackAndTools: backendUser.stackAndTools as string[] | undefined,
    workExperiences: backendUser.workExperiences as WorkExperience[] | undefined,
    education: backendUser.education as EducationItem[] | undefined,
    certifications: backendUser.certifications as CertificationItem[] | undefined,
    projects: backendUser.projects as ProjectItem[] | undefined,
    openSourceContributions: backendUser.openSourceContributions as OpenSourceContribution[] | undefined,
    mySetup: backendUser.mySetup as SetupItem[] | undefined,
    isGoogleAccount: backendUser.isGoogleAccount,
    isGitAccount: backendUser.isGitAccount,
    isFacebookAccount: backendUser.isFacebookAccount,
    isXAccount: backendUser.isXAccount,
    isAppleAccount: backendUser.isAppleAccount,
    createdAt: backendUser.createdAt,
  };
}
