/** Bootstrap rows for profile entity autocomplete (companies, schools, organizations). */

export type ReferenceEntitySeedRow = Readonly<{ name: string; domain: string }>;

export const COMPANY_REFERENCE_SEED: ReferenceEntitySeedRow[] = [
  { name: 'Microsoft', domain: 'microsoft.com' },
  { name: 'Google', domain: 'google.com' },
  { name: 'Apple', domain: 'apple.com' },
  { name: 'Amazon', domain: 'amazon.com' },
  { name: 'Meta', domain: 'meta.com' },
  { name: 'Facebook', domain: 'facebook.com' },
  { name: 'Tesla', domain: 'tesla.com' },
  { name: 'Netflix', domain: 'netflix.com' },
  { name: 'Adobe', domain: 'adobe.com' },
  { name: 'Salesforce', domain: 'salesforce.com' },
  { name: 'Oracle', domain: 'oracle.com' },
  { name: 'IBM', domain: 'ibm.com' },
  { name: 'Intel', domain: 'intel.com' },
  { name: 'Nvidia', domain: 'nvidia.com' },
  { name: 'Spotify', domain: 'spotify.com' },
  { name: 'Uber', domain: 'uber.com' },
  { name: 'Airbnb', domain: 'airbnb.com' },
  { name: 'Stripe', domain: 'stripe.com' },
  { name: 'Slack', domain: 'slack.com' },
  { name: 'GitHub', domain: 'github.com' },
  { name: 'Atlassian', domain: 'atlassian.com' },
  { name: 'LinkedIn', domain: 'linkedin.com' },
  { name: 'Twitter', domain: 'x.com' },
  { name: 'PayPal', domain: 'paypal.com' },
  { name: 'VMware', domain: 'vmware.com' },
  { name: 'Cisco', domain: 'cisco.com' },
  { name: 'SAP', domain: 'sap.com' },
  { name: 'Shopify', domain: 'shopify.com' },
  { name: 'Zoom', domain: 'zoom.us' },
  { name: 'Dropbox', domain: 'dropbox.com' },
  { name: 'Twitch', domain: 'twitch.tv' },
  { name: 'Red Hat', domain: 'redhat.com' },
  { name: 'Dell', domain: 'dell.com' },
  { name: 'HP', domain: 'hp.com' },
  { name: 'Accenture', domain: 'accenture.com' },
  { name: 'Deloitte', domain: 'deloitte.com' },
  { name: 'TCS', domain: 'tcs.com' },
  { name: 'Infosys', domain: 'infosys.com' },
  { name: 'Wipro', domain: 'wipro.com' },
];

export const SCHOOL_REFERENCE_SEED: ReferenceEntitySeedRow[] = [
  { name: 'MIT', domain: 'mit.edu' },
  { name: 'Stanford University', domain: 'stanford.edu' },
  { name: 'Harvard University', domain: 'harvard.edu' },
  { name: 'California Institute of Technology', domain: 'caltech.edu' },
  { name: 'University of Oxford', domain: 'ox.ac.uk' },
  { name: 'University of Cambridge', domain: 'cam.ac.uk' },
  { name: 'Carnegie Mellon University', domain: 'cmu.edu' },
  { name: 'University of California, Berkeley', domain: 'berkeley.edu' },
  { name: 'Georgia Institute of Technology', domain: 'gatech.edu' },
  { name: 'University of Washington', domain: 'uw.edu' },
  { name: 'Princeton University', domain: 'princeton.edu' },
  { name: 'Yale University', domain: 'yale.edu' },
  { name: 'Columbia University', domain: 'columbia.edu' },
  { name: 'University of Michigan', domain: 'umich.edu' },
  { name: 'University of Texas at Austin', domain: 'utexas.edu' },
  { name: 'Purdue University', domain: 'purdue.edu' },
  { name: 'University of Illinois', domain: 'illinois.edu' },
  { name: 'Cornell University', domain: 'cornell.edu' },
  { name: 'University of Southern California', domain: 'usc.edu' },
  { name: 'New York University', domain: 'nyu.edu' },
  { name: 'Boston University', domain: 'bu.edu' },
  { name: 'Northwestern University', domain: 'northwestern.edu' },
  { name: 'Duke University', domain: 'duke.edu' },
  { name: 'University of Edinburgh', domain: 'ed.ac.uk' },
  { name: 'ETH Zurich', domain: 'ethz.ch' },
  { name: 'IIT Bombay', domain: 'iitb.ac.in' },
  { name: 'IIT Delhi', domain: 'iitd.ac.in' },
  { name: 'BITS Pilani', domain: 'bits-pilani.ac.in' },
  { name: 'Indian Institute of Science', domain: 'iisc.ac.in' },
  { name: 'Delhi Technological University', domain: 'dtu.ac.in' },
];

export const ORGANIZATION_REFERENCE_SEED: ReferenceEntitySeedRow[] = [
  { name: 'AWS', domain: 'aws.amazon.com' },
  { name: 'Google Cloud', domain: 'cloud.google.com' },
  { name: 'Microsoft Learn', domain: 'microsoft.com' },
  { name: 'Coursera', domain: 'coursera.org' },
  { name: 'edX', domain: 'edx.org' },
  { name: 'Udemy', domain: 'udemy.com' },
  { name: 'LinkedIn Learning', domain: 'linkedin.com' },
  { name: 'CompTIA', domain: 'comptia.org' },
  { name: 'ISC2', domain: 'isc2.org' },
  { name: 'PMI', domain: 'pmi.org' },
  { name: 'IEEE', domain: 'ieee.org' },
  { name: 'ACM', domain: 'acm.org' },
  { name: 'Linux Foundation', domain: 'linuxfoundation.org' },
  { name: 'Free Code Camp', domain: 'freecodecamp.org' },
  { name: 'Codecademy', domain: 'codecademy.com' },
  { name: 'Pluralsight', domain: 'pluralsight.com' },
  { name: 'HackerRank', domain: 'hackerrank.com' },
  { name: 'LeetCode', domain: 'leetcode.com' },
  { name: 'IBM Skills Build', domain: 'ibm.com' },
  { name: 'Oracle University', domain: 'oracle.com' },
  { name: 'Salesforce Trailhead', domain: 'trailhead.salesforce.com' },
  { name: 'HashiCorp', domain: 'hashicorp.com' },
  { name: 'Red Hat Training', domain: 'redhat.com' },
  { name: 'Cisco NetAcad', domain: 'netacad.com' },
  { name: 'AWS Training', domain: 'aws.amazon.com' },
  { name: 'Google Developers', domain: 'developers.google.com' },
  { name: 'Microsoft Certification', domain: 'microsoft.com' },
  { name: 'Meta Blueprint', domain: 'facebook.com' },
  { name: 'Adobe Credential Program', domain: 'adobe.com' },
];
