import type { TechStackReferenceCategory } from "../models/TechStackReference.js";
export type TechStackSeedRow = {
  name: string;
  slug: string;
  category: TechStackReferenceCategory;
  iconSlug?: string;
};
export const TECH_STACK_REFERENCE_SEED: TechStackSeedRow[] = [
  { name: "React", slug: "react", category: "Frontend" },
  { name: "Next.js", slug: "nextjs", category: "Frontend", iconSlug: "nextjs" },
  { name: "Vue.js", slug: "vue", category: "Frontend", iconSlug: "vue" },
  { name: "Angular", slug: "angular", category: "Frontend" },
  { name: "Svelte", slug: "svelte", category: "Frontend" },
  {
    name: "TypeScript",
    slug: "typescript",
    category: "Language",
    iconSlug: "ts",
  },
  {
    name: "JavaScript",
    slug: "javascript",
    category: "Language",
    iconSlug: "js",
  },
  { name: "HTML", slug: "html", category: "Language" },
  { name: "CSS", slug: "css", category: "Language" },
  {
    name: "Tailwind CSS",
    slug: "tailwindcss",
    category: "Frontend",
    iconSlug: "tailwind",
  },
  { name: "Bootstrap", slug: "bootstrap", category: "Frontend" },
  { name: "Sass", slug: "sass", category: "Frontend" },
  { name: "Redux", slug: "redux", category: "Library" },
  { name: "Vite", slug: "vite", category: "Tool" },
  { name: "Webpack", slug: "webpack", category: "Tool" },
  {
    name: "Three.js",
    slug: "threejs",
    category: "Library",
    iconSlug: "threejs",
  },
  {
    name: "Material UI",
    slug: "materialui",
    category: "Library",
    iconSlug: "materialui",
  },
  { name: "Node.js", slug: "nodejs", category: "Backend", iconSlug: "nodejs" },
  { name: "Express", slug: "express", category: "Backend" },
  { name: "NestJS", slug: "nestjs", category: "Backend" },
  { name: "Python", slug: "python", category: "Language" },
  { name: "Django", slug: "django", category: "Backend" },
  { name: "Flask", slug: "flask", category: "Backend" },
  { name: "FastAPI", slug: "fastapi", category: "Backend" },
  { name: "Java", slug: "java", category: "Language" },
  { name: "Spring", slug: "spring", category: "Backend" },
  { name: "Go", slug: "golang", category: "Language", iconSlug: "golang" },
  { name: "Rust", slug: "rust", category: "Language" },
  { name: "PHP", slug: "php", category: "Language" },
  { name: "Laravel", slug: "laravel", category: "Backend" },
  { name: "Ruby", slug: "ruby", category: "Language" },
  { name: "Rails", slug: "rails", category: "Backend" },
  { name: "C#", slug: "csharp", category: "Language", iconSlug: "cs" },
  { name: ".NET", slug: "dotnet", category: "Backend", iconSlug: "dotnet" },
  { name: "GraphQL", slug: "graphql", category: "Backend" },
  { name: "Prisma", slug: "prisma", category: "Library" },
  { name: "Bun", slug: "bun", category: "Backend" },
  { name: "Deno", slug: "deno", category: "Backend" },
  { name: "Flutter", slug: "flutter", category: "Mobile" },
  { name: "Dart", slug: "dart", category: "Language" },
  { name: "Swift", slug: "swift", category: "Language" },
  { name: "Kotlin", slug: "kotlin", category: "Language" },
  {
    name: "React Native",
    slug: "react-native",
    category: "Mobile",
    iconSlug: "react",
  },
  {
    name: "Android Studio",
    slug: "androidstudio",
    category: "Tool",
    iconSlug: "androidstudio",
  },
  { name: "Xcode", slug: "xcode", category: "Tool" },
  { name: "MongoDB", slug: "mongodb", category: "Database" },
  {
    name: "PostgreSQL",
    slug: "postgresql",
    category: "Database",
    iconSlug: "postgresql",
  },
  { name: "MySQL", slug: "mysql", category: "Database" },
  { name: "Redis", slug: "redis", category: "Database" },
  { name: "SQLite", slug: "sqlite", category: "Database" },
  { name: "Elasticsearch", slug: "elasticsearch", category: "Database" },
  { name: "Supabase", slug: "supabase", category: "Database" },
  { name: "Firebase", slug: "firebase", category: "Database" },
  { name: "Docker", slug: "docker", category: "DevOps" },
  {
    name: "Kubernetes",
    slug: "kubernetes",
    category: "DevOps",
    iconSlug: "kubernetes",
  },
  { name: "Terraform", slug: "terraform", category: "DevOps" },
  { name: "AWS", slug: "aws", category: "Cloud" },
  { name: "Google Cloud", slug: "gcp", category: "Cloud", iconSlug: "gcp" },
  { name: "Azure", slug: "azure", category: "Cloud" },
  { name: "Linux", slug: "linux", category: "DevOps" },
  { name: "Nginx", slug: "nginx", category: "DevOps" },
  { name: "Git", slug: "git", category: "Tool" },
  { name: "GitHub", slug: "github", category: "Tool" },
  { name: "GitLab", slug: "gitlab", category: "Tool" },
  {
    name: "GitHub Actions",
    slug: "githubactions",
    category: "DevOps",
    iconSlug: "githubactions",
  },
  { name: "Jenkins", slug: "jenkins", category: "DevOps" },
  { name: "Ansible", slug: "ansible", category: "DevOps" },
  { name: "Cloudflare", slug: "cloudflare", category: "Cloud" },
  { name: "Vercel", slug: "vercel", category: "Cloud" },
  { name: "Netlify", slug: "netlify", category: "Cloud" },
  { name: "Heroku", slug: "heroku", category: "Cloud" },
  { name: "DigitalOcean", slug: "digitalocean", category: "Cloud" },
  { name: "Jest", slug: "jest", category: "Tool" },
  { name: "Cypress", slug: "cypress", category: "Tool" },
  { name: "Postman", slug: "postman", category: "Tool" },
  { name: "Insomnia", slug: "insomnia", category: "Tool" },
  { name: "VS Code", slug: "vscode", category: "Tool", iconSlug: "vscode" },
  { name: "npm", slug: "npm", category: "Tool" },
  { name: "pnpm", slug: "pnpm", category: "Tool" },
  { name: "Yarn", slug: "yarn", category: "Tool" },
  { name: "Electron", slug: "electron", category: "Tool" },
  { name: "Tauri", slug: "tauri", category: "Tool" },
  { name: "Figma", slug: "figma", category: "Design" },
  { name: "Sketch", slug: "sketch", category: "Design" },
  {
    name: "Adobe XD",
    slug: "adobexd",
    category: "Design",
    iconSlug: "adobexd",
  },
  { name: "Photoshop", slug: "photoshop", category: "Design" },
  { name: "Illustrator", slug: "illustrator", category: "Design" },
  { name: "Blender", slug: "blender", category: "Design" },
];
